---
    deployment:
     tasks:
     - export DEPLOYPATH=/home/tradaxge/public_html/api
     - /bin/cp index.php $DEPLOYPATH
     - /bin/cp .editorconfig $DEPLOYPATH
     - /bin/cp .env.example $DEPLOYPATH
     - /bin/cp .env $DEPLOYPATH
     - /bin/cp .gitattributes $DEPLOYPATH
     - /bin/cp .gitignore $DEPLOYPATH
     - /bin/cp .styleci.yml $DEPLOYPATH
     - /bin/cp README.md $DEPLOYPATH
     - /bin/cp app/Actions/Fortify/CreateNewUser.php $DEPLOYPATH
     - /bin/cp app/Actions/Fortify/PasswordValidationRules.php $DEPLOYPATH
     - /bin/cp app/Actions/Fortify/ResetUserPassword.php $DEPLOYPATH
     - /bin/cp app/Actions/Fortify/UpdateUserPassword.php $DEPLOYPATH
     - /bin/cp app/Actions/Fortify/UpdateUserProfileInformation.php $DEPLOYPATH
     - /bin/cp app/Actions/Jetstream/DeleteUser.php $DEPLOYPATH
     - /bin/cp app/Console/Kernel.php $DEPLOYPATH
     - /bin/cp app/Exceptions/Handler.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/AdminController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/Apis/AuthController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/Controller.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/CoursePlatform.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/CreateAddressController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/DevClearCacheController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/HomeController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/MerchantController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/Merchantp2pController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/PaymentController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/SmsController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/TradeController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/TrainingController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/TransactionsController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/TwoFAController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/UserController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/UsersController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/WalletController.php $DEPLOYPATH
     - /bin/cp app/Http/Controllers/WalletsController.php $DEPLOYPATH
     - /bin/cp app/Http/Kernel.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/Authenticate.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/EncryptCookies.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/PreventRequestsDuringMaintenance.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/RedirectIfAuthenticated.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/TokenIsValid.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/TrimStrings.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/TrustHosts.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/TrustProxies.php $DEPLOYPATH
     - /bin/cp app/Http/Middleware/VerifyCsrfToken.php $DEPLOYPATH
     - /bin/cp app/Http/Traits/Accounts.php $DEPLOYPATH
     - /bin/cp app/Http/Traits/Agreements.php $DEPLOYPATH
     - /bin/cp app/Http/Traits/CryptoBalance.php $DEPLOYPATH
     - /bin/cp app/Http/Traits/CryptoWallets.php $DEPLOYPATH
     - /bin/cp app/Http/Traits/Payments.php $DEPLOYPATH
     - /bin/cp app/Models/Assets.php $DEPLOYPATH
     - /bin/cp app/Models/Merchant.php $DEPLOYPATH
     - /bin/cp app/Models/Settings.php $DEPLOYPATH
     - /bin/cp app/Models/Transaction.php $DEPLOYPATH
     - /bin/cp app/Models/User.php $DEPLOYPATH
     - /bin/cp app/Models/VirtualAccount.php $DEPLOYPATH
     - /bin/cp app/Models/Wallet.php $DEPLOYPATH
     - /bin/cp app/Providers/AppServiceProvider.php $DEPLOYPATH
     - /bin/cp app/Providers/AuthServiceProvider.php $DEPLOYPATH
     - /bin/cp app/Providers/BroadcastServiceProvider.php $DEPLOYPATH
     - /bin/cp app/Providers/EventServiceProvider.php $DEPLOYPATH
     - /bin/cp app/Providers/FortifyServiceProvider.php $DEPLOYPATH
     - /bin/cp app/Providers/JetstreamServiceProvider.php $DEPLOYPATH
     - /bin/cp app/Providers/RouteServiceProvider.php $DEPLOYPATH
     - /bin/cp app/View/Components/AppLayout.php $DEPLOYPATH
     - /bin/cp app/View/Components/GuestLayout.php $DEPLOYPATH
     - /bin/cp bootstrap/app.php $DEPLOYPATH
     - /bin/cp bootstrap/cache/.gitignore $DEPLOYPATH
     - /bin/cp composer.json $DEPLOYPATH
     - /bin/cp composer.lock $DEPLOYPATH
     - /bin/cp config/app.php $DEPLOYPATH
     - /bin/cp config/auth.php $DEPLOYPATH
     - /bin/cp config/broadcasting.php $DEPLOYPATH
     - /bin/cp config/cache.php $DEPLOYPATH
     - /bin/cp config/cors.php $DEPLOYPATH
     - /bin/cp config/database.php $DEPLOYPATH
     - /bin/cp config/filesystems.php $DEPLOYPATH
     - /bin/cp config/fortify.php $DEPLOYPATH
     - /bin/cp config/hashing.php $DEPLOYPATH
     - /bin/cp config/jetstream.php $DEPLOYPATH
     - /bin/cp config/logging.php $DEPLOYPATH
     - /bin/cp config/mail.php $DEPLOYPATH
     - /bin/cp config/queue.php $DEPLOYPATH
     - /bin/cp config/sanctum.php $DEPLOYPATH
     - /bin/cp config/services.php $DEPLOYPATH
     - /bin/cp config/session.php $DEPLOYPATH
     - /bin/cp config/view.php $DEPLOYPATH
     - /bin/cp database/.gitignore $DEPLOYPATH
     - /bin/cp database/factories/UserFactory.php $DEPLOYPATH
     - /bin/cp database/migrations/2014_10_12_000000_create_users_table.php $DEPLOYPATH
     - /bin/cp database/migrations/2014_10_12_100000_create_password_resets_table.php $DEPLOYPATH
     - /bin/cp database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php $DEPLOYPATH
     - /bin/cp database/migrations/2019_08_19_000000_create_failed_jobs_table.php $DEPLOYPATH
     - /bin/cp database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php $DEPLOYPATH
     - /bin/cp database/migrations/2022_05_08_013054_create_sessions_table.php $DEPLOYPATH
     - /bin/cp database/seeders/DatabaseSeeder.php $DEPLOYPATH
     - /bin/cp lang/en/auth.php $DEPLOYPATH
     - /bin/cp lang/en/pagination.php $DEPLOYPATH
     - /bin/cp lang/en/passwords.php $DEPLOYPATH
     - /bin/cp lang/en/validation.php $DEPLOYPATH
     - /bin/cp package-lock.json $DEPLOYPATH
     - /bin/cp package.json $DEPLOYPATH
     - /bin/cp phpunit.xml $DEPLOYPATH
     - /bin/cp public/.htaccess $DEPLOYPATH
     - /bin/cp public/css/app.css $DEPLOYPATH
     - /bin/cp public/favicon.ico $DEPLOYPATH
     - /bin/cp public/index.php $DEPLOYPATH
     - /bin/cp public/js/app.js $DEPLOYPATH
     - /bin/cp public/mix-manifest.json $DEPLOYPATH
     - /bin/cp public/robots.txt $DEPLOYPATH
     - /bin/cp resources/css/app.css $DEPLOYPATH
     - /bin/cp resources/js/app.js $DEPLOYPATH
     - /bin/cp resources/js/bootstrap.js $DEPLOYPATH
     - /bin/cp resources/markdown/policy.md $DEPLOYPATH
     - /bin/cp resources/markdown/terms.md $DEPLOYPATH
     - /bin/cp resources/views/api/api-token-manager.blade.php $DEPLOYPATH
     - /bin/cp resources/views/api/index.blade.php $DEPLOYPATH
     - /bin/cp resources/views/auth/confirm-password.blade.php $DEPLOYPATH
     - /bin/cp resources/views/auth/forgot-password.blade.php $DEPLOYPATH
     - /bin/cp resources/views/auth/login.blade.php $DEPLOYPATH
     - /bin/cp resources/views/auth/register.blade.php $DEPLOYPATH
     - /bin/cp resources/views/auth/reset-password.blade.php $DEPLOYPATH
     - /bin/cp resources/views/auth/two-factor-challenge.blade.php $DEPLOYPATH
     - /bin/cp resources/views/auth/verify-email.blade.php $DEPLOYPATH
     - /bin/cp resources/views/dashboard.blade.php $DEPLOYPATH
     - /bin/cp resources/views/layouts/app.blade.php $DEPLOYPATH
     - /bin/cp resources/views/layouts/guest.blade.php $DEPLOYPATH
     - /bin/cp resources/views/navigation-menu.blade.php $DEPLOYPATH
     - /bin/cp resources/views/policy.blade.php $DEPLOYPATH
     - /bin/cp resources/views/profile/delete-user-form.blade.php $DEPLOYPATH
     - /bin/cp resources/views/profile/logout-other-browser-sessions-form.blade.php $DEPLOYPATH
     - /bin/cp resources/views/profile/show.blade.php $DEPLOYPATH
     - /bin/cp resources/views/profile/two-factor-authentication-form.blade.php $DEPLOYPATH
     - /bin/cp resources/views/profile/update-password-form.blade.php $DEPLOYPATH
     - /bin/cp resources/views/profile/update-profile-information-form.blade.php $DEPLOYPATH
     - /bin/cp resources/views/terms.blade.php $DEPLOYPATH
     - /bin/cp resources/views/welcome.blade.php $DEPLOYPATH
     - /bin/cp routes/api.php $DEPLOYPATH
     - /bin/cp routes/channels.php $DEPLOYPATH
     - /bin/cp routes/console.php $DEPLOYPATH
     - /bin/cp routes/web.php $DEPLOYPATH
     - /bin/cp storage/app/.gitignore $DEPLOYPATH
     - /bin/cp storage/app/public/.gitignore $DEPLOYPATH
     - /bin/cp storage/framework/.gitignore $DEPLOYPATH
     - /bin/cp storage/framework/cache/.gitignore $DEPLOYPATH
     - /bin/cp storage/framework/cache/data/.gitignore $DEPLOYPATH
     - /bin/cp storage/framework/sessions/.gitignore $DEPLOYPATH
     - /bin/cp storage/framework/testing/.gitignore $DEPLOYPATH
     - /bin/cp storage/framework/views/.gitignore $DEPLOYPATH
     - /bin/cp storage/logs/.gitignore $DEPLOYPATH
     - /bin/cp tailwind.config.js $DEPLOYPATH
     - /bin/cp tests/CreatesApplication.php $DEPLOYPATH
     - /bin/cp tests/Feature/ApiTokenPermissionsTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/AuthenticationTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/BrowserSessionsTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/CreateApiTokenTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/DeleteAccountTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/DeleteApiTokenTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/EmailVerificationTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/ExampleTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/PasswordConfirmationTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/PasswordResetTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/ProfileInformationTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/RegistrationTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/TwoFactorAuthenticationSettingsTest.php $DEPLOYPATH
     - /bin/cp tests/Feature/UpdatePasswordTest.php $DEPLOYPATH
     - /bin/cp tests/TestCase.php $DEPLOYPATH
     - /bin/cp tests/Unit/ExampleTest.php $DEPLOYPATH
     - /bin/cp webpack.mix.js $DEPLOYPATH